In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import torch.optim as optim
import numpy as np
import pickle
import os
import copy

In [ ]:
d = pickle.load(open('/home/gou/Downloads/comm/datasets/RML2016.10a/RML2016.10a_dict.pkl', 'rb'), encoding = 'latin-1')

In [ ]:
from conv import Convolution

In [ ]:
a = Convolution(3,10,3,1,'valid',0)

In [ ]:
if (2,3) == (2,3):
    raise ValueError('a')

In [ ]:
a(np.random.randn(10,3,25,25))

In [ ]:
a.backward(np.ones((10,10,23,23)))

In [ ]:
a.filters_grad

In [ ]:
import warnings

def fxn():
    warnings.warn("deprecated", DeprecationWarning)

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    fxn()


In [ ]:
warnings.warn('wrong')

In [ ]:
a

In [ ]:
a = np.random.randn(1,1,6,6)

In [ ]:
a

In [ ]:
a[:,:,0:0,0:0]

In [ ]:
list(np.array([1,23]))

In [ ]:
e = np.array([1,2,4])

In [ ]:
list(a[:,:,1,1])

In [ ]:
import mapper


In [ ]:
np.argmax(d[:,1,0:3,0:3].reshape(2,9), axis=1)

In [ ]:
d[:,:,:,0:7].shape

In [ ]:
d = np.random.randn(1,1,9,9)


In [ ]:
np.random.binomial(1,0.5,(2,20))

In [ ]:
np.argmax(d.reshape(5,100), axis=1)

In [ ]:
from maxpool import maxpool

In [ ]:
e = maxpool(3,stride=1,padding=4)



In [ ]:

e(d).shape

In [ ]:
e.backward(np.ones((1,1,15,15))).shape

In [ ]:
e.max_map

In [ ]:
e.max_map

In [ ]:
d

In [ ]:
d

In [ ]:
d.reshape(d.shape[0]*d.shape[1],)

In [ ]:
nn.Conv2d(3,6,6,)

In [ ]:
np.sum(d,axis=1).shape

In [ ]:
d[2].shape

In [ ]:
d

In [ ]:
np.set_printoptions(edgeitems=3,infstr='inf',
... linewidth=75, nanstr='nan', precision=8,
... suppress=False, threshold=1000, formatter=None)


In [ ]:
s = 

In [ ]:
d = np.random.rand(5,3)

In [ ]:
count = 1
for j in range(0,18-3,2):
    for k in range(0,18-3,2):
        print(j,k)
        count += 1
print(count)


In [ ]:
d = np.random.rand(3,4)
e = np.random.rand(3,4)
d,e

In [24]:
e = np.random.randn(12,10)

In [28]:
e

array([[-1.94141409e+00, -1.41802437e+00, -9.65345117e-01,
         5.69099021e-01,  9.37666679e-01, -6.04003921e-01,
         6.86946941e-01, -1.43514310e+00,  3.49711988e-01,
        -2.12401494e+00],
       [-2.28281784e+00,  5.23701033e-01,  1.74945870e+00,
         2.82971928e-01, -1.69499657e+00,  1.35454410e+00,
         6.70509249e-01, -5.04667147e-01,  1.48458278e+00,
        -1.08313622e-03],
       [ 5.97397739e-01, -2.16695414e-02,  4.15561365e-01,
        -6.39117035e-01, -8.90798135e-01, -1.65585942e+00,
         9.33092995e-01, -1.86585208e+00,  2.93998541e-01,
         5.98409444e-02],
       [-5.59260386e-01,  5.60034480e-02,  1.88950057e+00,
        -1.39410590e+00, -3.66397412e-01, -1.08575316e-01,
        -3.60952378e-01,  6.46932330e-01, -1.20537091e+00,
         2.21828623e-03],
       [ 5.40668818e-02, -1.07626399e-02, -1.74325505e+00,
         1.08032069e+00, -1.25433558e-01, -1.05158429e-01,
         5.48456862e-01, -1.30518870e+00,  5.75424934e-01,
        -7.

In [29]:
from batch_norm1d import batch_norm1d

In [13]:
d = batch_norm1d(10)

In [34]:
d(e)

array([[-1.33627886, -1.6304844 , -0.370494  ,  0.12926093,  1.01239625,
        -0.50200583, -0.18400493, -1.34684051, -0.29388136, -1.86795214],
       [-1.54361809,  0.34865434, -0.28388168, -0.05191864, -1.75254658,
        -0.13513269, -0.18997234, -0.48546943, -0.1257845 , -0.05968139],
       [ 0.20557677, -0.20722448, -0.32643796, -0.63579792, -0.90794076,
        -0.69903829, -0.09464605, -1.74556147, -0.30213362, -0.00778748],
       [-0.49687775, -0.12805488, -0.27941383, -1.11386716, -0.35719124,
        -0.40920267, -0.56442585,  0.5806027 , -0.52421996, -0.0568693 ],
       [-0.12439559, -0.19610743, -0.39531221,  0.45297346, -0.10412003,
        -0.40856262, -0.23428125, -1.22653761, -0.2604488 , -0.72550639],
       [-0.76359483,  0.45522354, -0.37770621, -0.53090078,  0.05289661,
        -0.66753437, -0.32168896, -1.4786756 , -0.48244403, -0.52494176],
       [ 0.47281289, -0.0973138 , -0.3155756 , -0.75962671, -0.38982793,
        -0.40404094,  0.18556537,  1.37602622

In [35]:
d.backward(np.random.randn(12,10))

array([[ 0.05545594, -1.25629759, -0.03925415,  1.21744488, -0.21048396,
        -0.08300424,  0.81775683, -1.12183585, -0.02329235, -0.32635074],
       [ 0.27886701,  1.97429841, -0.01572976,  0.58366928,  0.31308142,
        -0.09317368, -0.30686135, -0.51553351, -0.02227022,  0.91005549],
       [-1.40964241,  0.62920294,  0.00487394,  0.21489001,  1.19178541,
        -0.00961799, -0.18899001,  0.9700859 ,  0.13150445, -0.93867655],
       [ 0.65164597, -1.27023771,  0.005853  ,  0.70058975, -0.03437204,
        -0.14574784, -0.04052264,  0.92251987,  0.0234328 ,  0.91968351],
       [ 0.19174874, -0.66639224,  0.05397332,  0.47687256, -1.70846269,
        -0.0294554 , -0.42306665,  0.08674032,  0.04061349,  0.96066172],
       [ 0.34168086, -0.55210395, -0.02528175, -0.10995601,  1.34186557,
         0.06689284,  0.04602235, -0.12434065, -0.05403064,  0.70388011],
       [ 1.05157715,  0.28297654,  0.00793979,  0.23627624, -0.03897257,
         0.22078495, -0.03630578, -1.01180424

In [33]:
d.gradient_step(0.01)

In [37]:
d.gamma_grad

array([[ 2.81667157,  0.02654249,  1.32215986, -1.60521461,  0.76636598,
         0.73722326,  4.13816109, -0.07496798,  7.50445697,  1.77537284]])

In [ ]:
np.random.uniform(0,1,(1,10))

In [ ]:
"kkdf    dddfdf".split('    ')

In [ ]:
type(8.98) == float


In [ ]:
np.array([[1,2],[2,3],[2,2]]).shape

In [ ]:
0.00000002/0.11111111111111111111